import Head from 'next/head';
import {Banner, Header, MediumCard, SmallCard, LargeCard, Footer} from '@/components';
import {ICardData, IExploreData} from "@/model/data.model";

export default function Home({exploreData, cardsData}: { exploreData: IExploreData[], cardsData: ICardData[] }) {
    return (
        <>
            <Head>
                <title>Airbnb Like</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Header/>
                <Banner/>
                <main className="max-w-7xl mx-auto px-8 sm:px-16">
                    <section className="pt-6">
                        <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                            {exploreData?.map(({img, location, distance}, index) => (
                                <SmallCard key={index} img={img} location={location} distance={distance}/>
                            ))}
                        </div>
                    </section>
                    <section>
                        <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
                        <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
                            {cardsData?.map(({img, title}, index) => (
                                <MediumCard key={index} img={img} title={title}/>
                            ))}
                        </div>
                    </section>
                    <LargeCard img="https://links.papareact.com/4cj" title="The Greatest Outdoors"
                               description="Wishlists curated by Airbnb." buttonText="Get Inspired"/>
                </main>
                <Footer/>
            </div>
        </>
    )
};

export async function getStaticProps() {
    const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(res => res.json());
    const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(res => res.json());
    // const exploreData = await fetch("http://localhost:3000/api/explore").then(res => res.json());
    // const cardsData = await fetch("http://localhost:3000/api/cards").then(res => res.json());
    return {
        props: {
            exploreData,
            cardsData
        }
    }
}
